"""Constants for quiz-forge generation."""

import uuid

API_URL_TEMPLATE = "https://api.wikimedia.org/feed/v1/wikipedia/en/onthisday/events/{month}/{day}"
QUIZ_TYPE_WHICH_CAME_FIRST = "which_came_first"
QUIZ_TYPE_HISTORY_MCQ_4 = "history_mcq_4"
QUIZ_TYPE_HISTORY_FACTOID_MCQ_4 = "history_factoid_mcq_4"
QUIZ_TYPE_GEOGRAPHY_FACTOID_MCQ_4 = "geography_factoid_mcq_4"
SUPPORTED_QUIZ_TYPES = (
    QUIZ_TYPE_WHICH_CAME_FIRST,
    QUIZ_TYPE_HISTORY_MCQ_4,
    QUIZ_TYPE_HISTORY_FACTOID_MCQ_4,
    QUIZ_TYPE_GEOGRAPHY_FACTOID_MCQ_4,
)
DEFAULT_QUIZ_TYPES = ",".join(
    (QUIZ_TYPE_WHICH_CAME_FIRST, QUIZ_TYPE_HISTORY_MCQ_4, QUIZ_TYPE_HISTORY_FACTOID_MCQ_4)
)
DEFAULT_DAILY_EDITIONS_BY_TYPE = {
    QUIZ_TYPE_WHICH_CAME_FIRST: 1,
    QUIZ_TYPE_HISTORY_MCQ_4: 1,
    QUIZ_TYPE_HISTORY_FACTOID_MCQ_4: 3,
}
DEFAULT_DAILY_EDITIONS_BY_TYPE_STRING = ",".join(
    f"{quiz_type}={count}" for quiz_type, count in DEFAULT_DAILY_EDITIONS_BY_TYPE.items()
)
GENERATION_MODE_DAILY = "daily"
GENERATION_MODE_EXTRA = "extra"
SUPPORTED_GENERATION_MODES = (GENERATION_MODE_DAILY, GENERATION_MODE_EXTRA)
QUIZ_FILENAME_NAMESPACE = uuid.uuid5(uuid.NAMESPACE_URL, "mindblast.quiz-forge.daily.v1")
QUIZ_QUESTION_NAMESPACE = uuid.uuid5(uuid.NAMESPACE_URL, "mindblast.quiz-forge.question.v1")
ANSWER_FACT_NAMESPACE = uuid.uuid5(uuid.NAMESPACE_URL, "mindblast.quiz-forge.answer-fact.v1")
QUIZ_SCHEMA_VERSION = 2
NORMALIZED_MODEL_VERSION = "question_answer_facts_v1"
WHICH_CAME_FIRST_QUESTION = "Which event happened earlier?"
HUMAN_ID_LOOKUP_FILENAME = "human_id_lookup.json"
HUMAN_ID_LOOKUP_VERSION = 1
QUESTION_HUMAN_ID_PREFIX = "Q"
ANSWER_HUMAN_ID_PREFIX = "A"
AI_MODE_OFF = "off"
AI_MODE_SHADOW = "shadow"
AI_MODE_ON = "on"
SUPPORTED_AI_MODES = (AI_MODE_OFF, AI_MODE_SHADOW, AI_MODE_ON)
AI_PROVIDER_NOOP = "noop"
AI_PROVIDER_OPENAI = "openai"
AI_PROVIDER_OLLAMA = "ollama"
SUPPORTED_AI_PROVIDERS = (AI_PROVIDER_NOOP, AI_PROVIDER_OPENAI, AI_PROVIDER_OLLAMA)
AI_LEDGER_RELATIVE_PATH = "ai/usage_ledger.json"
